export const metadata = {
  title: "Privacy Policy | VirtusQ",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-black text-white px-6 md:px-16 py-24">
      <div className="max-w-4xl mx-auto space-y-10">

        <h1 className="text-4xl md:text-5xl font-bold">
          Privacy Policy
        </h1>

        <p className="text-zinc-400">
          Last updated: February 2026
        </p>

        <section className="space-y-6 text-zinc-300 leading-relaxed">

          <p>
            This Privacy Policy explains how VirtusQ collects,
            uses, and protects your information when you use
            our website and mobile application.
          </p>

          <h2 className="text-xl font-semibold text-white">1. Information We Collect</h2>
          <p>We may collect:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Email address (if provided)</li>
            <li>Uploaded videos for analysis</li>
            <li>Performance data generated by AI models</li>
            <li>Device and usage analytics</li>
          </ul>

          <h2 className="text-xl font-semibold text-white">2. How We Use Information</h2>
          <p>
            We use collected information to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Provide AI performance analysis</li>
            <li>Improve model accuracy</li>
            <li>Maintain service security</li>
            <li>Communicate updates</li>
          </ul>

          <h2 className="text-xl font-semibold text-white">3. Data Storage</h2>
          <p>
            Data may be stored securely on third-party cloud providers.
            We implement reasonable technical safeguards
            to protect your data.
          </p>

          <h2 className="text-xl font-semibold text-white">4. Video Content</h2>
          <p>
            Uploaded videos are processed for analysis purposes.
            We do not sell or publicly distribute user-uploaded content.
          </p>

          <h2 className="text-xl font-semibold text-white">5. Cookies & Analytics</h2>
          <p>
            We may use cookies or analytics tools
            to improve performance and user experience.
          </p>

          <h2 className="text-xl font-semibold text-white">6. Data Sharing</h2>
          <p>
            We do not sell personal information.
            Data may be shared with trusted service providers
            strictly for operational purposes.
          </p>

          <h2 className="text-xl font-semibold text-white">7. Your Rights</h2>
          <p>
            You may request access, correction,
            or deletion of your personal information
            by contacting us.
          </p>

          <h2 className="text-xl font-semibold text-white">8. Security</h2>
          <p>
            While we implement safeguards,
            no system is completely secure.
            Use of the Service is at your own risk.
          </p>

          <h2 className="text-xl font-semibold text-white">9. Changes to Policy</h2>
          <p>
            We may update this Privacy Policy.
            Continued use of the Service
            constitutes acceptance of updates.
          </p>

          <h2 className="text-xl font-semibold text-white">10. Contact</h2>
          <p>
            support@virtusq.com
          </p>

        </section>
      </div>
    </main>
  );
}
