export const metadata = {
  title: "Privacy Policy | VirtusQ",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-black text-white px-6 md:px-16 py-24">
      <div className="max-w-4xl mx-auto space-y-10">

        <h1 className="text-4xl md:text-5xl font-bold">
          Privacy Policy
        </h1>

        <p className="text-zinc-400">
          Last updated: February 2026
        </p>

        <section className="space-y-6 text-zinc-300 leading-relaxed">

          <p>
            This Privacy Policy explains how VirtusQ collects,
            uses, stores, and protects your information when you use
            our website and mobile application.
          </p>

          <h2 className="text-xl font-semibold text-white">1. Information We Collect</h2>
          <p>We may collect the following types of information:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Email address (if provided by you)</li>
            <li>Uploaded videos and media content for analysis</li>
            <li>Performance data generated by AI models</li>
            <li>Device information (such as device type, OS, and identifiers)</li>
            <li>Usage data and analytics (including interactions within the app)</li>
          </ul>

          <h2 className="text-xl font-semibold text-white">2. How We Use Information</h2>
          <p>
            We use collected information to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Provide AI-powered performance analysis and features</li>
            <li>Improve model accuracy and app functionality</li>
            <li>Maintain security, prevent fraud, and ensure service integrity</li>
            <li>Communicate with users regarding updates or support</li>
            <li>Comply with legal obligations</li>
          </ul>

          <h2 className="text-xl font-semibold text-white">3. Legal Basis for Processing</h2>
          <p>
            We process your information where necessary to provide our services,
            fulfill contractual obligations, comply with legal requirements,
            or based on your consent where applicable.
          </p>

          <h2 className="text-xl font-semibold text-white">4. Data Storage and Retention</h2>
          <p>
            Data may be stored securely on third-party cloud providers.
            We retain personal data only for as long as necessary to provide
            our services, comply with legal obligations, and resolve disputes.
          </p>

          <h2 className="text-xl font-semibold text-white">5. Video Content</h2>
          <p>
            Uploaded videos are processed solely for analysis and feature functionality.
            We do not sell, rent, or publicly distribute user-uploaded content.
            You retain ownership of your content.
          </p>

          <h2 className="text-xl font-semibold text-white">6. Cookies & Analytics</h2>
          <p>
            We may use cookies, analytics tools, and similar technologies
            to improve app performance, understand usage patterns,
            and enhance user experience.
          </p>

          <h2 className="text-xl font-semibold text-white">7. Data Sharing</h2>
          <p>
            We do not sell personal information.
            We may share data with trusted third-party service providers
            (such as hosting, analytics, and infrastructure providers)
            strictly to operate and improve our services.
          </p>

          <h2 className="text-xl font-semibold text-white">8. International Data Transfers</h2>
          <p>
            Your information may be processed and stored in countries
            outside your region. We take reasonable steps to ensure
            appropriate safeguards are in place for such transfers.
          </p>

          <h2 className="text-xl font-semibold text-white">9. Your Rights</h2>
          <p>
            Depending on your location, you may have the right to access,
            correct, delete, or restrict the use of your personal data.
            You may also withdraw consent where applicable by contacting us.
          </p>

          <h2 className="text-xl font-semibold text-white">10. Children’s Privacy</h2>
          <p>
            Our services are not intended for children under the age of 13
            (or the minimum legal age in your jurisdiction). We do not knowingly
            collect personal information from children.
          </p>

          <h2 className="text-xl font-semibold text-white">11. Security</h2>
          <p>
            We implement reasonable administrative, technical,
            and organizational safeguards to protect your data.
            However, no system is completely secure.
          </p>

          <h2 className="text-xl font-semibold text-white">12. Changes to Policy</h2>
          <p>
            We may update this Privacy Policy from time to time.
            Continued use of the Service constitutes acceptance
            of any updates.
          </p>

          <h2 className="text-xl font-semibold text-white">13. Contact</h2>
          <p>
            virtusqsup@gmail.com
          </p>

        </section>
      </div>
    </main>
  );
}
