// ============================================================
// PRIVACY POLICY PAGE
// Save as: app/privacy/page.tsx
// ============================================================

import Link from "next/link";

export const metadata = {
  title: "Privacy Policy | VirtusQ",
};

const PRIVACY_SECTIONS = [
  {
    num: "01",
    title: "Information We Collect",
    body: `We may collect your email address (if provided), videos uploaded for analysis, performance data generated by AI models, and device and usage analytics.`,
  },
  {
    num: "02",
    title: "How We Use Information",
    body: `We use collected information to provide AI performance analysis, improve model accuracy, maintain service security, and communicate updates.`,
  },
  {
    num: "03",
    title: "Data Storage",
    body: `Data may be stored securely on third-party cloud providers. We implement reasonable technical safeguards to protect your data.`,
  },
  {
    num: "04",
    title: "Video Content",
    body: `Uploaded videos are processed for analysis purposes only. We do not sell or publicly distribute user-uploaded content.`,
  },
  {
    num: "05",
    title: "Cookies & Analytics",
    body: `We may use cookies or analytics tools to improve performance and user experience.`,
  },
  {
    num: "06",
    title: "Data Sharing",
    body: `We do not sell personal information. Data may be shared with trusted service providers strictly for operational purposes.`,
  },
  {
    num: "07",
    title: "Your Rights",
    body: `You may request access, correction, or deletion of your personal information. You can delete your account directly within the app by navigating to Settings and selecting "Delete Account". When you delete your account, your account and all associated personal data will be permanently deleted. This action cannot be undone. If you are unable to access the app, you may also request deletion by contacting us at virtusqsup@gmail.com.`,
  },
  {
    num: "08",
    title: "Security",
    body: `While we implement safeguards, no system is completely secure. Use of the Service is at your own risk.`,
  },
  {
    num: "09",
    title: "Changes to Policy",
    body: `We may update this Privacy Policy periodically. Continued use of the Service constitutes acceptance of updates.`,
  },
  {
    num: "10",
    title: "Contact",
    body: `For privacy-related questions or data requests, contact us at virtusqsup@gmail.com`,
  },
];

export default function PrivacyPage() {
  return (
    <main style={{ backgroundColor: "#080808", color: "#f0f0f0", minHeight: "100vh" }}>
      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "clamp(100px, 15vw, 160px) 24px 80px" }}>

        {/* Back */}
        <Link
          href="/"
          style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.72rem", letterSpacing: "0.1em", color: "#63ffb4", textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "6px", marginBottom: "3rem" }}
        >
          ← VIRTUSQ
        </Link>

        {/* Header */}
        <p style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.72rem", letterSpacing: "0.12em", color: "#63ffb4", marginBottom: "1rem", textTransform: "uppercase" }}>
          Legal
        </p>
        <h1
          style={{
            fontFamily: "'DM Serif Display', serif",
            fontSize: "clamp(2.2rem, 5vw, 3.5rem)",
            fontWeight: 400, color: "#f0f0f0",
            lineHeight: 1.1, marginBottom: "1rem",
          }}
        >
          Privacy Policy
        </h1>
        <p style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", color: "rgba(240,240,240,0.3)", letterSpacing: "0.06em", marginBottom: "3.5rem" }}>
          LAST UPDATED: FEBRUARY 2026
        </p>

        <p style={{ fontSize: "0.95rem", lineHeight: 1.8, color: "rgba(240,240,240,0.55)", marginBottom: "3rem" }}>
          This Privacy Policy explains how VirtusQ collects, uses, and protects your information when you use our website and mobile application.
        </p>

        {/* Sections */}
        <div style={{ display: "flex", flexDirection: "column", gap: "2.5rem" }}>
          {PRIVACY_SECTIONS.map((s) => (
            <div key={s.num} style={{ display: "flex", gap: "1.5rem" }}>
              <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.72rem", color: "#63ffb4", fontWeight: 700, flexShrink: 0, marginTop: "4px", minWidth: "24px" }}>
                {s.num}
              </span>
              <div>
                <h2 style={{ fontFamily: "'DM Serif Display', serif", fontSize: "1.15rem", fontWeight: 400, color: "#f0f0f0", marginBottom: "0.6rem" }}>
                  {s.title}
                </h2>
                <p style={{ fontSize: "0.92rem", lineHeight: 1.8, color: "rgba(240,240,240,0.5)" }}>
                  {s.body}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
